variable "instance_template_name" {}
variable "instance_template_machine_type" {}
variable "instance_template_image" {}
variable "instance_template_disk_size" {}
variable "instance_template_disk_type" {}
variable "instance_template_network_name" {}
variable "instance_template_tags" {}
variable "instance_template_labels" {}
variable "instance_template_subnetwork_id" {}